"use strict";
exports.__esModule = true;
var entrenador_1 = require("./entrenador");
var jugador_1 = require("./jugador");
var masajista_1 = require("./masajista");
var posicion_1 = require("./posicion");
var kineseologo = new masajista_1.Masajista("celeste y blanca", "Francisco Ledezma", "4562187988", "5 de noviembre", 2023, 100000, "kineseología");
var posicion = new posicion_1.Posicion(10, "delantero", "marcar Goles y asistir");
var Messi = new jugador_1.Jugador("celeste y blanca", "lionel Messi", "356488456528", "25 de junio", 2023, 20000, posicion, "PSG", true);
console.log(Messi);
console.log(Messi.renewContract());
console.log("se acord\u00F3 un aumento de ".concat(Messi.salario));
console.log(Messi.aptoJuego());
var posicionJugador = new posicion_1.Posicion(21, "Arquero", "Defender el arco, atajar goles");
var dibu = new jugador_1.Jugador("verde", "Emiliano Martínez", "356548799", "3 de marzo", 2024, 15000, posicionJugador, "Manchester United", false);
console.log(dibu);
console.log(dibu.renewContract());
console.log("Se acord\u00F3 un aumento de ".concat(dibu.salario));
console.log(dibu.aptoJuego());
console.log(kineseologo.realizarMasajes());
var DTScalonni = new entrenador_1.Entrenador("Azul", "Lionel Scalonni", "272794652218", "5 de abril", 2022, 60000, false);
console.log(DTScalonni);
console.log(DTScalonni.organizarJugada());
